site_name: Hosam Mohamed

repo_url: https://github.com/hmae
repo_name: github Profile
copyright: Copyright Ⓒ 2025 hmae

# extra:
#   homepage: https://google.com

# theme: readthedocs
theme:
  name: material
  palette:
    primary: teal
    accent: orange

    
  favicon: hello.jpg
nav:
  - Resume : /index.html
  - Portfolio: portfolio.md

markdown_extensions:
  - attr_list
  - md_in_html
  - tables

plugins:
  - search